export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

export const LOAD_PROBLEMS_SUCCESS = 'LOAD_PROBLEMS_SUCCESS';
export const CREATE_PROBLEM_SUCCESS = 'CREATE_PROBLEM_SUCCESS';
export const UPDATE_PROBLEM_SUCCESS = 'UPDATE_PROBLEM_SUCCESS';